Feature: Union schema compatibility
fivetran/dbt_google_play_source pull request #14
Opened 2024-07-15 17:49 UTC by fivetran-catfritz

Issue: 

Confirm the following files were correctly updated automatically:
- [ ] CHANGELOG
- [ ] README
- [ ] stg_google_play.yml, src_google_play.yml, google_play.yml (depending if source or transform)
- [ ] docs.md
- [ ] joins
- [ ] window functions (partition by)
- [ ] 'source_relation' column added in staging and transform models
- [ ] tests

Manual updates:
- [ ] Add `source_relation` to downstream models if necessary
- [ ] Finish any incomplete/incorrect joins/partitions
- [ ] Update tests to include `source_relation` in unique-combination-of-cols if necessary
    - May need to remove some uniqueness tests in favor of the combo test

Validation:
- [ ] `dbt run` locally passes
- [ ] `dbt test` locally passes

2024-07-19 21:32 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz this PR is looking good, just a few small requests.

2024-07-19 21:32 UTC, fivetran-joemarkiewicz commented on models/stg_google_play__store_performance_source.sql
>          {{ dbt_utils.generate_surrogate_key(['date', 'package_name', 'traffic_source', 'search_term', 'utm_campaign', 'utm_source']) }} as traffic_source_unique_key,
Shouldn't the source_relation be included here as well?

2024-07-19 21:32 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
Please apply the same notes from the Apple store PR to this CHANGELOG as well.

2024-07-19 21:40 UTC, fivetran-joemarkiewicz commented
Also before merging we should add the auto releaser to this package.

2024-07-22 21:03 UTC, fivetran-catfritz reviewed
@fivetran-joemarkiewicz I have updated, including the changes from apple_store. This is ready for re-review!

2024-07-22 21:03 UTC, fivetran-catfritz commented on models/stg_google_play__store_performance_source.sql
>          {{ dbt_utils.generate_surrogate_key(['date', 'package_name', 'traffic_source', 'search_term', 'utm_campaign', 'utm_source']) }} as traffic_source_unique_key,
Ahh I wasn't 100% on this one. In this model, the surrogate key appears to only be used only for the uniqueness test and not downstream. But now that you mention it, it would make sense to add to it here so there's no question. Added!

2024-07-22 21:09 UTC, fivetran-joemarkiewicz approved these changes
LGTM thanks for applying the updates!

2024-07-23 22:12 UTC, merged